---
- name: Check HTTP server output
  hosts: all
  vars:
  ipv4_address
  tasks:
   - command
     “{{ ansible_facts.all_ipv4_addresses }}”
     sed 's/“[u'172.31.45.39']”/172.31.45.39/g'
   - get_url:
      url: http://“{{ ansible_facts.all_ipv4_addresses }}”
      dest: /tmp/
